name: tf-install
inputs:
  version:
    required: false
    default: 0.12.24
  os:
    required: false
    default: linux
  arch:
    required: false
    default: amd64
runs:
  using: composite
  steps:
  - name: download Terraform
    run: |-
      curl -L -o /tmp/terraform.zip \
      https://releases.hashicorp.com/terraform/${{ inputs.version }}/terraform_${{ inputs.version }}_${{ inputs.os }}_${{ inputs.arch }}.zip
    shell: bash
  - run: unzip -d /go/bin /tmp/terraform.zip
    shell: bash